### ISSUE TITLE
Compilation failure on 7.6.3

### ISSUE THREAD

**Issue by adamgundry** [haskell/win32#118]
With GHC 7.6.3, the latest version (2.8.1.0) is selected by cabal's solver but fails to build with:
```
Building library for Win32-2.8.1.0..
GraphicsWin32Window.hsc:2:14:
    Unsupported extension: NegativeLiterals
```
If you don't want to support GHCs this old (fair enough!) would you remind revising the bound on `base` to reflect supported versions, so that cabal will select an older version as needed?

See https://ci.appveyor.com/project/adamgundry/acid-state/build/job/b79whx1g7h85sgop for a build log.

**Comment by hvr** [comment]
Alternatively, if the `.cabal` file had this declared via `other-extensions: NegativeLiterals` the solver would also have avoided it w/ GHC versions which don't provide that extensions

**Comment by Mistuke** [comment]
Thanks for the report, I don't actually support `7.6`, I only currently go only back to `7.8`, however in this case the changes required to not use this extension are minimal so I will patch that up.

**Comment by Mistuke** [comment]
> 
> 
> Alternatively, if the `.cabal` file had this declared via `other-extensions: NegativeLiterals` the solver would also have avoided it w/ GHC versions which don't provide that extensions

Ah thanks, that's useful to know.

**Comment by Mistuke** [comment]
#119 Will fix this, will release tomorrow.

**Comment by adamgundry** [comment]
Thanks for the quick turnaround! I can confirm that 2.8.2.0 builds with 7.6.3.
