### ISSUE TITLE
win32 package no longer on stackage

### ISSUE THREAD

**Issue by hanjoosten** [haskell/win32#127]
In previous times, win32 was [available on stackage](https://www.stackage.org/package/Win32/snapshots). The last version available was version 2.5.4.1. After [LTS 11.7](https://www.stackage.org/diff/lts-11.7/lts-11.8), win32 is no longer available. 

To me, it is unclear if this is on purpose. Maybe something is broken.

**Comment by Mistuke** [comment]
That seems like a question for stackage people. Nothing different has been done for the later releases.

**Comment by Mistuke** [comment]
closing this as it's an issue for stackage curators.
