### ISSUE TITLE
Bump version and cut release for GHC 7.8.1

### ISSUE THREAD

**Issue by hvr** [haskell/win32#13]
Currently, GHC HEAD still reports `Win32-2.3.0.0` in its package registry (which is incorrect, as 2.3.0.0 is what GHC 7.6.3 shipped with, and there have been non-trivial commits since then)

Moreover, the GHC 7.8.1 release candidate is getting closer, and we should get the boot lib versioning in order asap.

/cc @thoughtpolice

**Comment by hvr** [comment]
Fwiw, GHC 7.10.1RC3 will finally ship with `Win32-2.3.1.0` thanks to ghc/ghc@e935a7f4584f02e67196bb1f1978b32f0fdb310c

**Comment by Mistuke** [comment]
Since this has been done, closing the issue
