### ISSUE TITLE
OVERLAPPED Storable instance - address violation error

### ISSUE THREAD

**Issue by coot** [haskell/win32#141]
The 'OVERLAPPED' 'Storable' instance should check if the `ovl_hEvent' pointer is not null, otherwise it will result in an address violation error:
https://hackage.haskell.org/package/Win32-2.8.5.0/docs/src/System.Win32.File.html#line-650

**Comment by Mistuke** [comment]
I don't follow. It deference the address of the pointer, not the pointer itself. The location should always be valid regardless of it's content.

**Comment by coot** [comment]
You're right.
