### ISSUE TITLE
The scope of this package?

### ISSUE THREAD

**Issue by TravisWhitaker** [haskell/win32#144]
I'm curious how it is decided what parts of the Win32 api make it into this package or not. On the one hand, there's decent coverage of a bunch of UI areas (e.g. GDI) but certain things are strangely absent (e.g. radio buttons can be created, but not Rebars). On the other hand, certain lower-level things are missing (I just found that AllocConsole was missing).

I'm guessing we're in one of two situations:
- Since this is a boot package, only some curated "core" of Win32 functionality is included to keep library size manageable.
- Since the Win32 API is massive, things have been added piecemeal as they're needed.

In the latter case, I'd be happy to help add some missing parts! In the former case, I'm curious how this subset was chosen.

**Comment by Mistuke** [comment]
It's no# 2, there is just too many APIs and so we add bindings as needed. There are only a couple of restrictions:

1. If you name an API the same as on MSDN, then the behavior should be the same. i.e. no convenience wrappers with the same name as the API but with different semantics.  The wrappers are welcomed, just with a different name.

2. We can't take on external dependencies.  This complicates GHC bootstrapping.

3. We need to maintain compatibility with much older GHCs, as such we have compat files to fill in missing headers etc from older compilers.

And that's it really.  any PRs are always welcomed!

**Comment by TravisWhitaker** [comment]
Nice, thanks!
