### ISSUE TITLE
Hackage not up to date

### ISSUE THREAD

**Issue by javalight** [haskell/win32#156]
Hackage win32 still showing older repo, is this normal behavior? Is it supposed to update automatically with changes to github repo?

**Comment by Mistuke** [comment]
No, Hackage only has releases. This repository has in development versions as well. 

I do releases once a month and then next one is scheduled for end of Sept https://github.com/haskell/win32/milestones unless anyone has a need to get a release out sooner.

If you or @mpilgrem need a release with your changes I can do so, if not in general I stick to the monthly schedule.
