### ISSUE TITLE
Fishy instance for `Storable LASTINPUTINFO`

### ISSUE THREAD

**Issue by AndreasPK** [haskell/win32#172]
I think the definition of alignment for the instance is problematic as it might not be a power of two.

## Current Behavior

Currently this is defined as:

```haskell
instance Storable LASTINPUTINFO where
    sizeOf = const (#size LASTINPUTINFO)
    alignment = sizeOf
    ...
```

So `alignment` might end up being 123. It's fair to assume that alignment should be a power of two here.
This didn't cause issues in the past. But some functions in base on GHC HEAD now actually check alignment
and will fail with an error if the alignment isn't a power of two.

Another instance of this kind already caused issues for GHC (https://gitlab.haskell.org/ghc/ghc/-/issues/19392). So I looked for other occurences and found this instance.

------------

It could be fixed with a utility function like the one below which GHC should be able to evaluate at compile time.

```
{-# INLINE alignmentFromSize #-}
-- Return the next largest power of two if the argument isn't one already.
alignmentFromSize :: Int -> Int
alignmentFromSize size
    | isPowerOfTwo size = size
    | otherwise = alignment
    where
        isPowerOfTwo :: (Bits i, Integral i) => i -> Bool
        isPowerOfTwo x = x .&. (x-1) == 0
        -- Rounding down
        logBase2 x = finiteBitSize x - 1 - countLeadingZeros x
        -- Get the next power of two
        alignment = 2^(logBase2 size + 1)
```

Then the instance can define alignment as `alignment = alignmentFromSize . sizeOf`

**Comment by RyanGlScott** [comment]
Better yet, why not just use `#alignment LASTINPUTINFO` to compute its alignment directly?

**Comment by AndreasPK** [comment]
> Better yet, why not just use `#alignment LASTINPUTINFO` to compute its alignment directly?

I read some comment of that being only supported by "somewhat" recent versions. But depending on the version constraints that should work as well I guess.

**Comment by RyanGlScott** [comment]
`#alignment` works out of the box on GHC 8.0 or later, but it's straightforward to backport to older GHCs with enough CPP. In fact, `Win32` already does this—see `alignment.h`:

https://github.com/haskell/win32/blob/1fa775e13938d331c151141e3db05b85c16e02e4/include/alignment.h#L1-L3

As long as you `#include "alignment.h"`, all should be well.

**Comment by Mistuke** [comment]
Indeed, we should use `#alignment` here, Thanks for spotting this.. these modules came from an import of win32-extras and I thought I had gotten all the shady alignments.. but clearly missed one.

I'll go over the `Storable` instances again and double check them.

**Comment by Mistuke** [comment]
Fixed, thanks for the report.
