### ISSUE TITLE
Change maxLength to 16 in function getComputerName

### ISSUE THREAD

**Issue by gussen** [haskell/win32#189]
Change maxLength to 16 in function getComputerName

## Current Behavior
My computername is DESKTOP-28LPP05 (15 characters) and when I call getComputerName I get error: 
GetComputerName: invalid argument (The file name is too long.)

If I set maxLength = 16 inside the function, getComputerName, it works as expected, I get the computername back.
 
## Steps to Reproduce (for bugs)
Set a computername that is 15 characters long and call getComputerName.

## Your Environment
* Operating System and version: Windows 10, Version 10.0.19043 Build 19043
* GHC 8.10.7. 
* As far as I can see the issue exists in all versions of Win32.

**Comment by Mistuke** [comment]
Fixed, thanks for the report!
