### ISSUE TITLE
Provide `GetTempFileNameW`

### ISSUE THREAD

**Issue by hasufell** [haskell/win32#204]
https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-gettempfilenamew

While working on a AFPP PR for the directory package I stumbled over the missing `openBinaryTempFile` function that's only defined for `FilePath`. Using Win32 bindings is probably easier than copy-pasting code from `base`.

**Comment by hasufell** [comment]
Has this been released?

**Comment by Mistuke** [comment]
> Has this been released?

Yes, as 2.14.1.0
