### ISSUE TITLE
createFile without busy-wait

### ISSUE THREAD

**Issue by joeyh** [haskell/win32#208]
createFile uses failIfWithRetry, and in my application, that busy-waiting for up to 2 seconds got in the way. I want to be able to open a file and give up immediately if there's something else that has it open.

I used to use `c_createFile` for this, but it got removed in https://github.com/haskell/win32/issues/174

I see that was an accidental export, but would you consider exporting the same functionality under some better name?

**Comment by Mistuke** [comment]
Hi, Yes I'm happy to export it under a different name

**Comment by joeyh** [comment]
Cool. I don't want to bikeshed on a name, but would it perhaps make sense to have a separate module for the closer-to-the-metal versions of functions?

**Comment by Mistuke** [comment]
No, close to the metal was always the intended version of the functions. It's an exception when there's a wrapper around it.

That createFile has the convenience functionality exposed under the default name is am exception.

**Comment by joeyh** [comment]
Thanks for merging this @Mistuke!

I don't know what your plans are for a release, but it would be helpful to me if this could get released sometime soonish. I am blocked from updating to a current stack lts by this, and so am stuck building against an old version of aeson that has a security hole..

**Comment by Mistuke** [comment]
Oh I think I simply forgot to do a release. I'll do it now.

**Comment by Mistuke** [comment]
Releasing through #215
