### ISSUE TITLE
Is it possible to use this package to control the Microsoft Excel application?

### ISSUE THREAD

**Issue by LastsForever** [haskell/win32#212]
Is it possible to use this package to control the Microsoft Excel application?

**Comment by Mistuke** [comment]
Hi, no, this package doesn't have vsto bindings. It's hard to interact with COM from Haskell. I recommend you go through a C layer first.

**Comment by LastsForever** [comment]
> Hi, no, this package doesn't have vsto bindings. It's hard to interact with COM from Haskell. I recommend you go through a C layer first.

Thanks
