### ISSUE TITLE
Make hackage revision for 2.13.3.0

### ISSUE THREAD

**Issue by hasufell** [haskell/win32#227]
2.13.3.0 needs to have an upper bound on `filepath <1.5`, otherwise we can get build failures like so: https://github.com/hasufell/file-io/actions/runs/7168798482/job/19517761687#step:5:111

@Bodigrim

**Comment by Mistuke** [comment]
Hmm I already made the revision two weeks ago.

**Comment by Mistuke** [comment]
Ah I made 2.13.4.0 fair enough..

**Comment by Mistuke** [comment]
Done.
