### ISSUE TITLE
Please build and upload documentation to Hackage

### ISSUE THREAD

**Issue by andreasabel** [haskell/win32#231]
Please build and upload documentation for Win32-2.14 to Hackage.

**Comment by Kleidukos** [comment]
@Mistuke Could you please do this when you find the time? :)

**Comment by Mistuke** [comment]
The documentation is built as part of the release, but ever since the OsString support its been failing with a weird error that I can't figure out. I'll try updating haddock and see

**Comment by Kleidukos** [comment]
Thank you 🫶

**Comment by AndreasPK** [comment]
Any update? Ran into this today.

**Comment by Mistuke** [comment]
docs uploaded https://hackage.haskell.org/package/Win32-2.14.0.0
