### ISSUE TITLE
Tag missing for release 2.14.0 

### ISSUE THREAD

**Issue by wz1000** [haskell/win32#235]
It looks like we don't have a tag for release 2.14.0, I think it corresponds to commit https://github.com/haskell/win32/commit/350ebd43f9a8d9e1ca767b0000f95bdfb42a5471

**Comment by Mistuke** [comment]
Ah thanks, looks like the release script didn't finish all the way. Will look into it and the docs issue more today.

**Comment by Mistuke** [comment]
Fixed and fixed CI
