### ISSUE TITLE
(Maybe String) parameters in API functions

### ISSUE THREAD

**Issue by a3f** [haskell/win32#24]
There are quite some functions with optional `LPTSTR` parameters in the Winpi, where passing `NULL` invokes the default behaviour. An example for this is FindWindow [(msdn)](http://msdn.microsoft.com/en-us/library/windows/desktop/ms633499%28v=vs.85%29.aspx).

The available Haskell wrappers don't support passing `NULL` to these functions.
The solution would be using `Maybe String` and writing a new `withTString` that returns `nullPtr` if `Nothing` is passed to it (i.e.: `Maybe String -> (CString -> IO a) -> IO a`). I can't find any readily available way to achieve the same, so I would make a group of functions à la `withOptCWString` and so on.

I'd be glad to give something back to the community by doing these changes, but as this also affects `Foreign.C.String` in ghc-base I wanted to ask for guidance first whether that's the right way to go :)

**Comment by mikesteele81** [comment]
@a3f,

In cases like your example of `findWindow` I usually re wrap the lower-level variant (`c_findWindow` in this case) within my own local Windows module. The higher-level function's source can be used as a template, so it's usually pretty straightforward.

I agree with you that it would be nice to have more convenient ways of supplying null pointers to common functions like this one.

**Comment by m37** [comment]
@a3f, @ygale,

I am wondering if it would be better to just change the signatures for these functions, instead of adding a whole lot of new, nearly-duplicate functions to accomplish this goal.

One reason (and a bit off-topic) for this is I noticed a very large number of functions (100+?)  that have incorrect type signatures, usually due to using `Int` instead of `CInt` or another type, and also some more serious offenses.  I was working on a pull request for that, about 1/2 done right now.  Anyway, the only way to fix those is to change the type signatures (breaking backwards-compatibility), so why not just bite the bullet and do the same here?

**Comment by ndmitchell** [comment]
My thoughts are similar to @m37 here, probably they should be `Maybe String` in the API properly. The hacky workarounds don't seem to make it that much easier to be compatible, and make it nasty forevermore. I think the number of people using Win32 directly is relatively low (in contrast to the vast number that use it indirectly) so fixing the relatively small number of people impacted should be feasible. [Disclaimer, I don't think it breaks any of my code, so I might be a  little bit less concerned than I otherwise would be.]

**Comment by ygale** [comment]
@ndmitchell I also agree that the approach of @m37 is really the best, at least theoretically. We also would feel very little direct impact. But do you have any estimate of how much breakage there would likely be on Hackage, and in Windows builds of GHC, if we go that way?

**Comment by ndmitchell** [comment]
On hackage there are 74 dependencies on Win32: http://packdeps.haskellers.com/reverse/Win32 - I guess a random sampling would probably give us the number that use relevant packages. No idea about GHC, but I suspect that's not too bad at all. Note that upgrading in a reverse compatible way should only be 5 lines, roughly:

    #if Win32_min_version(2,5,0)
    just = Just
    #else
    just = id
    #endif

Then just add `just` in front of the necessary arguments.

**Comment by ygale** [comment]
Elliot Robertson [posted this](http://mail.haskell.org/pipermail/libraries/2015-March/025228.html) on the libraries list:

> A quick reverse search [0] shows 74 packages having Win32 as a direct dependency, 3 of which are out of date. The big ones that stand out to me are `directory` (which will be up to Phil and me to fix) and `process` (which is maintained by Michael Snoyman (@snoyberg, ping)). Both are GHC dependencies, and each has 800+ reverse dependencies, so the release timing there will need to be well managed (possibly to coincide with the next major GHC RC?).
>
> This being said, I'm definitely in favor of better Win32 support. If it takes some extra effort to fix long-standing defects, that's the price of doing business.

**Comment by snoyberg** [comment]
I don't have lots of experience using the Win32 library directly, though I have touched it a few times. I don't have a strong feeling on this issue, but I tend to agreeing with this being a change worth making (despite my normal hesitancy around breaking changes). If there's a branch of win32 available to test against, I'd be happy to test out `process` against it and see how much breakage ensues.

**Comment by ygale** [comment]
A few other important potentially affected packages that caught my eye:

* cabal-install
* haskeline
* unix-compat
* time
* HTTP

**Comment by ygale** [comment]
I posted to the [café](http://mail.haskell.org/pipermail/haskell-cafe/2015-March/118712.html) and to [reddit](http://www.reddit.com/r/haskell/comments/2zi23e/proposed_significant_breaking_changes_to_win32/) to make sure that everyone who needs to know about this will know. So far everyone seems to be positive, so I think it's time to work on getting an actual patch ready. @a3f and @m37, do you already have some work? Can you coordinate on it, or someone just do it?

**Comment by tejon** [comment]
In via reddit and for whatever my barely-invested newbie's opinion is worth, this seems like a great idea. I'd be on the fence if it were just the `Maybe` change, but @a3f pointing out those other type issues puts it over the top.

**Comment by m37** [comment]
@ygale,

I do have some code that I was working on, it's been a bit since I touched it but I think I'm about 1/2 way done.  It doesn't include the changes to `Maybe` types like @a3f was working on, so I think if @a3f works on that part, and I continue on the rest, we probably won't overlap and our work would merge nicely.  I'm open to other suggestions though.

**Comment by a3f** [comment]
@ygale,

I also had some code done but then got lazy. I am willing to get this patch done though (I would dare say it mostly is).

I faced a design choice for which I need some input though:
In `Foreign.C.String`, we have:
`peekCAString :: CString -> IO String`
Now it ought to be either
`peekCAString :: CString -> Maybe (IO String)`
or
`peekCAString :: CString -> IO (Maybe String)`

Same goes for the other functions. Which one should we go for?
`Maybe (IO String)` makes the most sense, as there is no IO involved in case of a nullPtr, you just return Nothing.
`IO (Maybe String)` appears to be easier to work with.

I agree with @m37, I don't think there the eventual patches would interfere much with each other. I also agree on the point that the older signatures should be removed.

@mikesteele81
Ye, that's what I went with.

**Comment by rwbarton** [comment]
@a3f, I would go with the type signature that matches the function's intended use, namely `peekCAString :: CString -> IO (Maybe String)`, particularly as, if someone needed the `Maybe (IO String)` version for some reason, it's quite a trivial function to recreate.

**Comment by hgolden** [comment]
Because this is a breaking change, I suggest keeping the existing Win32 as old-win32 for a couple of releases at least. I would expect the support cost to be small, since there would be little or no changes to the old (often incorrect) functions.

**Comment by 3noch** [comment]
Just wanted to pitch my vote for the "breaking changes" approach. Haskell on Win32 is already a tad bit rough. If we pick an ugly backwards compatible approach, I deeply fear we would sacrifice "forward compatibility" (i.e. Win32 usage would only *decrease* because of superfluous complexity).

**Comment by Mistuke** [comment]
Hmm does anyone know what ever happened to this proposal/change?
