### ISSUE TITLE
Hackage docs

### ISSUE THREAD

**Issue by mlacorte** [haskell/win32#30]
Would you mind manually uploading the documentation for this library to Hackage? Their auto-generated docs fail since this library requires linking to some Windows only code which their build servers don't have.

The easiest way to do it is to use [this script](https://gist.github.com/Fuuzetsu/8276421).

Thanks.

**Comment by NightRa** [comment]
:+1:

**Comment by expipiplus1** [comment]
The uploaded documentation was incomplete, there are still missing docs on Hackage.

**Comment by hvr** [comment]
I generated docs for 2.3.1.1 via

    cabal haddock --for-hackage --haddock-options=--hyperlinked-source

and uploaded those. If there's need to generate docs retroactively for older versions let me or @Mistuke know.
