### ISSUE TITLE
Allow conversion from Handle -> HANDLE

### ISSUE THREAD

**Issue by agentm** [haskell/win32#51]
In writing cross-platform Haskell, I have a Handle but need to convert it to a HANDLE for use with System.Win32.File.

There is a private implementation [in ansi-terminal](http://hdiff.luite.com/cgit/ansi-terminal/tree/System/Console/ANSI/Windows/Foreign.hs#n302).

**Comment by Mistuke** [comment]
Hi, if you could provide a stripped down implementation I will add it, otherwise I'll try my best to get it into the next release.
