### ISSUE TITLE
Function to detect if GHC is running in MinTTY

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/win32#62]
GHC will soon have support for detecting whether it's running in MinTTY (Cygwin/MSYS2/etc.). The code for detecting this looks something like this.

```haskell
queryCygwinTerminal :: Win32.HANDLE -> IO Bool
queryCygwinTerminal h = do
    fileType <- Win32.getFileType h
    if fileType /= Win32.fILE_TYPE_PIPE
      then pure False
      else do
        fn <- getFileNameByHandle h
        pure (("\\cygwin-" `isPrefixOf` fn || "\\msys-" `isPrefixOf` fn) &&
              "-pty" `isInfixOf` fn &&
              "-master" `isSuffixOf` fn)
  `catch` \ (_ :: IOError) ->
    pure False

getFileNameByHandle :: Win32.HANDLE -> IO String
getFileNameByHandle h = do
  let sizeOfDWORD = sizeOf (undefined :: Win32.DWORD)
  let sizeOfWchar = sizeOf (undefined :: CWchar)
  -- note: implicitly assuming that DWORD has stronger alignment than wchar_t
  let bufSize = sizeOfDWORD + mAX_PATH * sizeOfWchar
  allocaBytes bufSize $ \ buf -> do
    getFileInformationByHandleEx h fileNameInfo buf (fromIntegral bufSize)
    len :: Win32.DWORD <- peek buf
    let len' = fromIntegral len `div` sizeOfWchar
    peekCWStringLen (buf `plusPtr` sizeOfDWORD, min len' mAX_PATH)

getFileInformationByHandleEx
  :: Win32.HANDLE -> CInt -> Ptr a -> Win32.DWORD -> IO ()
getFileInformationByHandleEx h cls buf bufSize = do
  lib <- Win32.getModuleHandle (Just "kernel32.dll")
  ptr <- Win32.getProcAddress lib "GetFileInformationByHandleEx"
  let c_GetFileInformationByHandleEx =
        mk_GetFileInformationByHandleEx (castPtrToFunPtr ptr)
  Win32.failIfFalse_ "getFileInformationByHandleEx"
    (c_GetFileInformationByHandleEx h cls buf bufSize)

type F_GetFileInformationByHandleEx a =
  Win32.HANDLE -> CInt -> Ptr a -> Win32.DWORD -> IO Win32.BOOL

foreign import WINAPI "dynamic"
  mk_GetFileInformationByHandleEx
  :: FunPtr (F_GetFileInformationByHandleEx a)
  -> F_GetFileInformationByHandleEx a
```

We should add something like this to `Win32`.

The problem is that [`GetFileInformationByHandleEx`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa364953(v=vs.85).aspx) was only introduced in Windows Vista. We should try to have a version that can also support Windows earlier than Vista. @Mistuke tells me this should be possible using [`NtQueryObject`](https://msdn.microsoft.com/en-us/library/bb432383(v=vs.85).aspx).

**Comment by RyanGlScott** [comment]
I'm not sure what this issue's relationship with [GHC Trac #12958](https://ghc.haskell.org/trac/ghc/ticket/12958) is (which requests for the same thing, but in C).

**Comment by Mistuke** [comment]
Hmm, don't really know a good way to share the code. We could implement it purely in C and just provide Haskell bindings to the simplified C code, and have `ghci.c` link against that. 

Or we can just provide a simplified version for `ghci.c` since we don't need pre-vista support in GHC anymore.
