### ISSUE TITLE
alignment implementations are wrong for most Storable instances in Win32

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/win32#66]
There are several `Storable` instances in `Win32`, but most of them implement `alignment` like so (example taken from [`System.Win32.Mem`](https://github.com/haskell/win32/blob/bfefef083637e48e164696cdd560c59e2d6883c5/System/Win32/Mem.hsc#L49-L51)):

```haskell
instance Storable MEMORY_BASIC_INFORMATION where
    sizeOf _ = #size MEMORY_BASIC_INFORMATION
    alignment = sizeOf
```

Defining `alignment = sizeOf` is usually wrong, and in the case of `MEMORY_BASIC_INFORMATION`, it's _definitely_ wrong, as this C program shows:

```c
#include <windows.h>
#include <inttypes.h>
#include <stdio.h>

int main(int argc, char **argv) {
    printf("Size: %" PRIu64 ", alignment: %" PRIu64 "\n",
           sizeof(MEMORY_BASIC_INFORMATION),
           __alignof__(MEMORY_BASIC_INFORMATION));

    return 0;
}
```
```
$ ./foo.exe
Size: 48, alignment: 8
```

We should define `alignment` properly using `hsc2hs`'s `#alignment` macro, introduced in GHC 8.0. Or, on older versions of GHC, use this `hsc2hs` macro:

```c
#if __GLASGOW_HASKELL__ < 711
#let alignment t = "%lu", (unsigned long)offsetof(struct {char x__; t (y__); }, y__)
#endif
```

**Comment by Mistuke** [comment]
Wtf!? I hadn't noticed that before. But yeah those are clearly wrong... I'll correct them before the next release.
