### ISSUE TITLE
build failure 'INPUT' undeclared

### ISSUE THREAD

**Issue by joeyh** [haskell/win32#90]
Win32-2.5 (and I think also 2.6) fails to build on a Windows system. This had been previously using Win32-2.4, which built ok. The problem is in the new System.Win32.Automation module.

> Failed to install Win32-2.5.4.1
> Build log ( C:\Users\jenkins\AppData\Roaming\cabal\logs\Win32-2.5.4.1.log ):
> Building Win32-2.5.4.1...
> Preprocessing library Win32-2.5.4.1...
> Input.hsc: In function 'main':
> Input.hsc:73:5: error: 'INPUT' undeclared (first use in this function)
> Input.hsc:73:5: note: each undeclared identifier is reported only once for each function it appears in
> Input.hsc:74:5: error: expected specifier-qualifier-list before 'INPUT'
> Input.hsc:74:5: error: 'struct <anonymous>' has no member named 'y__'
> Input.hsc:77:5: error: expected specifier-qualifier-list before 'INPUT'
> Input.hsc:77:5: error: expected ';' before ')' token
> Input.hsc:77:5: error: expected statement before ')' token
> Input.hsc:78:5: error: expected specifier-qualifier-list before 'INPUT'
> Input.hsc:78:5: error: expected ';' before ')' token
> Input.hsc:78:5: error: expected statement before ')' token
> Input.hsc:80:5: error: expected specifier-qualifier-list before 'INPUT'
> Input.hsc:80:5: error: expected ';' before ')' token
> Input.hsc:80:5: error: expected statement before ')' token
> Input.hsc:81:5: error: expected specifier-qualifier-list before 'INPUT'
> Input.hsc:81:5: error: expected ';' before ')' token
> Input.hsc:81:5: error: expected statement before ')' token
> Input.hsc:83:5: error: expected specifier-qualifier-list before 'INPUT'
> Input.hsc:83:5: error: expected ';' before ')' token
> Input.hsc:83:5: error: expected statement before ')' token
> Input.hsc:84:5: error: expected specifier-qualifier-list before 'INPUT'
> Input.hsc:84:5: error: expected ';' before ')' token
> Input.hsc:84:5: error: expected statement before ')' token
> Input.hsc:87:5: error: expected specifier-qualifier-list before 'INPUT'
> Input.hsc:87:5: error: expected ';' before ')' token
> Input.hsc:87:5: error: expected statement before ')' token
> Input.hsc:90:5: error: expected specifier-qualifier-list before 'INPUT'
> Input.hsc:90:5: error: expected ';' before ')' token
> Input.hsc:90:5: error: expected statement before ')' token
> Input.hsc:92:5: error: expected specifier-qualifier-list before 'INPUT'
> Input.hsc:92:5: error: expected ';' before ')' token
> Input.hsc:92:5: error: expected statement before ')' token
> Input.hsc:93:5: error: expected specifier-qualifier-list before 'INPUT'
> Input.hsc:93:5: error: expected ';' before ')' token
> Input.hsc:93:5: error: expected statement before ')' token
> Input.hsc:105:5: error: 'HARDWAREINPUT' undeclared (first use in this function)
> Input.hsc:106:5: error: expected specifier-qualifier-list before 'HARDWAREINPUT'
> Input.hsc:106:5: error: 'struct <anonymous>' has no member named 'y__'
> Input.hsc:108:5: error: expected specifier-qualifier-list before 'HARDWAREINPUT'
> Input.hsc:108:5: error: expected ';' before ')' token
> Input.hsc:108:5: error: expected statement before ')' token
> Input.hsc:109:5: error: expected specifier-qualifier-list before 'HARDWAREINPUT'
> Input.hsc:109:5: error: expected ';' before ')' token
> Input.hsc:109:5: error: expected statement before ')' token
> Input.hsc:110:5: error: expected specifier-qualifier-list before 'HARDWAREINPUT'
> Input.hsc:110:5: error: expected ';' before ')' token
> Input.hsc:110:5: error: expected statement before ')' token
> Input.hsc:112:5: error: expected specifier-qualifier-list before 'HARDWAREINPUT'
> Input.hsc:112:5: error: expected ';' before ')' token
> Input.hsc:112:5: error: expected statement before ')' token
> Input.hsc:113:5: error: expected specifier-qualifier-list before 'HARDWAREINPUT'
> Input.hsc:113:5: error: expected ';' before ')' token
> Input.hsc:113:5: error: expected statement before ')' token
> Input.hsc:114:5: error: expected specifier-qualifier-list before 'HARDWAREINPUT'
> Input.hsc:114:5: error: expected ';' before ')' token
> Input.hsc:114:5: error: expected statement before ')' token
> compiling dist\build\System\Win32\Automation\Input_hsc_make.c failed (exit code 1)
> command was: c:\haskell\7.10.2-a\mingw\bin\gcc.exe -c dist\build\System\Win32\Automation\Input_hsc_make.c -o dist\build\System\Win32\Automation\Input_hsc_make.o -D__GLASGOW_HASKELL__=710 -Dmingw32_BUILD_OS=1 -Di386_BUILD_ARCH=1 -Dmingw32_HOST_OS=1 -Di386_HOST_ARCH=1 -Iinclude -fno-strict-aliasing -Wall -Idist\build\autogen -include dist\build\autogen\cabal_macros.h -IC:\haskell\7.10.2-a\lib\bytes_6elQVSg5cWdFrvRnfxTUrH\include -IC:\haskell\7.10.2-a\lib\base_GDytRqRVSUX7zckgKqJjgw\include -IC:\haskell\7.10.2-a\lib\integ_2aU3IZNMF9a7mQ0OzsZ0dS\include -IC:\haskell\7.10.2-a\lib/include -IC:\haskell\7.10.2-a/lib/include/

**Comment by joeyh** [comment]
Seems that was using ghc 7.10.2, which is quite old by now.

**Comment by Mistuke** [comment]
The problem is that GHC `7.10.2` uses an ancient `GCC 4.5.2` which contains very out of date header files. Would you be able to use anything never like even `7.10.3`? Maintaining `7.10.2` compatibility with the never stuff would require large in-lining of windows headers which I would rather avoid if I didn't need to..

**Comment by joeyh** [comment]
Yeah, I'm seeing a lot of header-type breakage in various libraries
that used to build ok. A ghc upgrade is in order.

-- 
see shy jo
